---
shared:
  image: buildpack-deps


jobs:
  deploy_homologacao:
    requires: [~pr, ~commit]
    # image: sqitch-oracle:latest
    environment:
      ORDEM_DEPLOY: ("TESTE" "BLA")
      USER_SHELL_BIN: bash
    steps:
      - sqitch: echo "deploy homologação"
      - teste: |
          echo ${ORDEM_DEPLOY[0]}
          echo ${ORDEM_DEPLOY[1]}

  testes_unitarios:
    requires: deploy_homologacao
    steps:
      - utplsql: echo "testes unitarios"

  publica_testes_e_coverage:
    requires: testes_unitarios
    steps:
      - publica_resultados: echo "publica resultados"
      - set_resultado_testes_e_coverage: |
          meta set tests.coverage 100
          meta set tests.results 10/10
  
  verifica_se_cobertura_ok:
    requires: publica_testes_e_coverage
    steps:
      - verifica_porcentagem_cobertura_codigo: echo "verifica porcentagem cobertura codigo"
  