---
shared:
  image: buildpack-deps


jobs:
  deploy_homologacao:
    requires: [~pr, ~commit]
    # image: sqitch-oracle:latest
    environment:
      ORDEM_DEPLOY: "Age/Parametros, Age/Clientes/CMHS/Parametros, Age/Objetos/Geral"
      USER_SHELL_BIN: bash
    steps:
      - sqitch: echo "deploy homologação"
      - teste: |
          IFS="," read -a ORDEM_DEPLOY_PROJETOS_SQITCH <<< $(echo "$ORDEM_DEPLOY" | tr -d " ")
          for projeto_sqitch in ${ORDEM_DEPLOY_PROJETOS_SQITCH[@]}; do
            echo $projeto_sqitch
          done

  testes_unitarios:
    requires: deploy_homologacao
    steps:
      - utplsql: echo "testes unitarios"

  publica_testes_e_coverage:
    requires: testes_unitarios
    steps:
      - publica_resultados: echo "publica resultados"
      - set_resultado_testes_e_coverage: |
          meta set tests.coverage 100
          meta set tests.results 10/10
  
  verifica_se_cobertura_ok:
    requires: publica_testes_e_coverage
    steps:
      - verifica_porcentagem_cobertura_codigo: echo "verifica porcentagem cobertura codigo"
  