---
shared:
  image: buildpack-deps


jobs:
  deploy_homologacao:
    requires: [~pr, ~commit]
    steps:
      - sqitch: echo "deploy homologação"

  testes_unitarios:
    requires: deploy_homologacao
    steps:
      - utplsql: echo "testes unitarios"

  publica_resultados_testes:
    requires: testes_unitarios
    steps:
      - publica_resultados: echo "publica resultados"
      - set-resultado-testes-e-cobertura: |
          meta set tests.coverage 100
          meta set tests.results 10/10
  
  verifica_se_cobertura_ok:
    requires: publica_resultados_testes
    steps:
      - verifica_porcentagem_cobertura_codigo: echo "verifica porcentagem cobertura codigo"
  